### ISSUE TITLE
Update Akladian Homeguard spirtes. Please.

### ISSUE THREAD

**Issue by knyghtmare** [cooljeanius/A_New_Order#8]
They have imapct attacks, but the present sprites use swords.
Use these. They were made by Edwylm on the Art Workshop forum.

![new akl-homeguard](https://user-images.githubusercontent.com/5283677/117991225-ac5d6900-b35f-11eb-9d24-fc558a45bcda.png)
![new akl-protector](https://user-images.githubusercontent.com/5283677/117991231-ad8e9600-b35f-11eb-87c8-6cf7f0d346fa.png)
![new akl-shieldguard](https://user-images.githubusercontent.com/5283677/117991236-ae272c80-b35f-11eb-8700-5050b38bc6fa.png)

Transfer the issue to the main repo if you want.

**Comment by cooljeanius** [comment]
> They have imapct attacks, but the present sprites use swords.
> Use these. They were made by Edwylm on the Art Workshop forum.
> 
> ![new akl-homeguard](https://user-images.githubusercontent.com/5283677/117991225-ac5d6900-b35f-11eb-9d24-fc558a45bcda.png)
> ![new akl-protector](https://user-images.githubusercontent.com/5283677/117991231-ad8e9600-b35f-11eb-87c8-6cf7f0d346fa.png)
> ![new akl-shieldguard](https://user-images.githubusercontent.com/5283677/117991236-ae272c80-b35f-11eb-8700-5050b38bc6fa.png)
> 
> Transfer the issue to the main repo if you want.

Main repo already has [neamaara/A_New_Order/11](https://github.com/nemaara/A_New_Order/issues/11); would this be enough to fix it?

**Comment by cooljeanius** [comment]
ok fixed for this repo by ac9bcfd; contributing it back upstream is a separate issue

**Comment by cooljeanius** [comment]
> ok fixed for this repo by [ac9bcfd](https://github.com/cooljeanius/A_New_Order/commit/ac9bcfd68010db8281a8c03e68fbf15072c46dac); contributing it back upstream is a separate issue

ok that's [nemaara/A_New_Order/13](https://github.com/nemaara/A_New_Order/pull/13) now.

**Comment by cooljeanius** [comment]
Note that this caused mismatches with their portraits:
* Homeguard portrait still has it holding a sword: https://units.wesnoth.org/1.16/A_New_Order/en_US/Akladian%20Homeguard.html
* Shieldguard portrait still has it holding a spear: https://units.wesnoth.org/1.16/A_New_Order/en_US/Akladian%20Shieldguard.html
* Protector portrait still has it holding a sword: https://units.wesnoth.org/1.16/A_New_Order/en_US/Akladian%20Protector.html
